### ISSUE TITLE
DAG enhancement

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#371]
## Feature Request 
Example: https://staging.dockstore.org/workflows/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/oxog-preprocessor

1. **GUI**: `filter` is not a tool, the node in DAG tab should be different compare to real tool (e.g node is grayed out, or edges from it is a dotted line). `filter` is not supposed to be in Tool tab since it is not a real Tool (this part had been implemented).
2. **Web Service**: Currently, the DAG edges are connected by the order(i.e 0 -> 1 -> 2 -> 3.....), but this is not always true, example:
```
gather_sanger_snvs:
      in:
        clean_vcfs:
            source: clean/clean_vcf
        extracted_snvs:
            source: extract_snv/extracted_snvs
      out: [snvs_for_merge]
      run:
        class: ExpressionTool
        inputs:
          clean_vcfs: File[]
          extracted_snvs: File[]
        outputs:
          snvs_for_merge: File[]
        expression: |
            $({ snvs_for_merge: (filterFor("svcp","snv_mnv",inputs.clean_vcfs)).concat(filterFor("svcp","snv_mnv",inputs.extracted_snvs)) })

    gather_dkfz_embl_snvs:
      in:
        clean_vcfs:
            source: clean/clean_vcf
        extracted_snvs:
            source: extract_snv/extracted_snvs
      out: [snvs_for_merge]
      run:
        class: ExpressionTool
        inputs:
          clean_vcfs: File[]
          extracted_snvs: File[]
        outputs:
          snvs_for_merge: File[]
        expression: |
            $({ snvs_for_merge: filterFor("dkfz-snvCalling","snv_mnv",inputs.clean_vcfs).concat(filterFor("dkfz-snvCalling","snv_mnv",inputs.extracted_snvs)) })

    gather_broad_snvs:
      in:
        clean_vcfs:
            source: clean/clean_vcf
        extracted_snvs:
            source: extract_snv/extracted_snvs
      out: [snvs_for_merge]
      run:
        class: ExpressionTool
        inputs:
          clean_vcfs: File[]
          extracted_snvs: File[]
        outputs:
          snvs_for_merge: File[]
        expression: |
            $({ snvs_for_merge: filterFor("broad-mutect","snv_mnv",inputs.clean_vcfs).concat(filterFor("broad-mutect","snv_mnv",inputs.extracted_snvs)) })
...
...
...
```
- As it can be seen from the example, `gather_sanger_snvs` ,`gather_dkfz_embl_snvs` ,`gather_broad_snvs` are all getting the input from `clean/clean_vcf` and `extract_snv/extracted_snvs` and output in `merge_vcfs`. 
- The current implementation will result in `... -> extract_snv -> gather_sanger_snvs -> gather_dkfz_embl_snvs -> gather_broad_snvs -> ... -> merge_vcfs`
- The correct DAG would have `extract_snv -> gather_sanger_snvs`, `extract_snv -> gather_dkfz_embl_snvs` and `extract_snv -> gather_broad_snvs` AND all of them merged/pointing back again to `merge_vcfs`
