### ISSUE TITLE
cwl2json should understand CWL arrays

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#534]
### Expected behaviour

```
  bams_in:
    type:
    - 'null'
    - type: array
      items: File
    doc: ""
    inputBinding:
      position: 6
```
should give 
```
  "bams_in": [
    {"class": "File",
      "path": "/tmp/test_in.bam"}
  ],
```

### Actual behaviour

We only do the simplified
```
"bams_in": "fill me in",
```

### Environment (Browser or OS and Dockstore version)
1.1
