### ISSUE TITLE
`tool convert cwl2json` needs better error message with invalid CWL

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#569]
## Bug Report

I'm trying to create JSON from [this CWL](https://github.com/ga4gh/dockstore/files/694312/varscan_cwl.txt).
This works:
`cwltool --non-strict --print-pre varscan.cwl > test.json`
And the resulting json [is valid](http://jsonlint.com/)

However, `dockstore tool convert` dies with `The JSON file provided is invalid` *without giving the offending JSON input*. So I can't tell what it's trying to do.

### Expected behaviour
Create json file

### Actual behaviour
```
The JSON file provided is invalid.
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: This is not a JSON Array.
```
### Steps to reproduce the behaviour 
`dockstore tool convert cwl2json --cwl varscan.cwl | tee varscan.json`
input: [varscan.cwl](https://github.com/ga4gh/dockstore/files/694312/varscan_cwl.txt)

### Environment (Browser or OS and Dockstore version)
`dockstore v1.1.1`
`Ubuntu 16.04`

**Comment by denis-yuen** [comment]
@Jeltje 

Hi, I took a look at this. I think the issue here is that the CWL is actually invalid, but somehow it passes pre-processing with cwltool which ends up tripping up our code. 

The end of varscan.cwl contains 
```
arguments:

  normal_pileup:
    type: string
    doc: |
      normal pileup file
    inputBinding:
      position: 3
      prefix: -normal_pileup

  tumor_pileup:
    type: string
    doc: |
      tumor pileup file
    inputBinding:
      position: 4
      prefix: -tumor_pileup
```

However, this doesn't seem like the right syntax. According to http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineTool arguments are not directed associated with input parameters (meaning they don't take an input binding). Instead, the fields that they have are the following http://www.commonwl.org/v1.0/CommandLineTool.html#CommandLineBinding so you could go for example

```
arguments:

  - prefix: -normal_pileup
    position: 3
  - previx: -tumor_pileup
    position: 4
```
