### ISSUE TITLE
Globbed output files should be provisionable to directory

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#724]
### Desired behaviour

Requested by @keiranmraine

Currently, we handle arrays in the following format ( https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/arrays.cwl and https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/testArrayHttpInputLocalOutput.json )
i.e. mapping an output file to an output file or mapping an output array of files to an output array of files. 

It looks like we're missing the case where an output array of files can be provisioned to an output directory. 

```
outputs:
  output:
    type:
      type: array
      items: File
    outputBinding:
      glob:
        - "*.fq"
        - "*.fq.gz"
        - "*.fa"
        - "*.fa.gz"
```
to
```
 "output": {
    "path": "/tmp/fun/",
    "class": "Directory"
  }
```

IIRC, we have code supporting secondary files that supports a similar use-case and may be re-used to implement this
https://raw.githubusercontent.com/ga4gh/dockstore/develop/dockstore-client/src/test/resources/split.cwl and https://raw.githubusercontent.com/ga4gh/dockstore/develop/dockstore-client/src/test/resources/split.json

Currently, this executes with no errors but the output files are not provisioned elsewhere 

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1
